// Libraries
import Head from 'next/head';

// Components
import Header from '../Components/Header';
import axios from 'axios';
import { CardsItems } from '../typings';
import CarouselImage from '../Components/CarouselImage';
import Cards from '../Components/Cards';

type Props = { cardsItems: CardsItems[] };

export default function Home({}: Props) {
    // JSX
    return (
        <>
            <Head>
                <title>Ludivine Serrurier</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <meta
                    name='viewport'
                    content='width=device-width, initial-scale=1'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>
            <main>
                <section className='flex flex-col'>
                    <header className='absolute z-20 top-0 py-2 px-4 bg-[#3D9BE9] w-full'>
                        <Header />
                    </header>
                    <section className='relative w-full h-screen'>
                        <CarouselImage />
                    </section>
                </section>
                <section className='h-screen flex flex-col items-center justify-center'>
                    <h3 className='w-[60%] text-4xl text-blue-200 drop-shadow-md font-semibold italic container pb-12 mx-auto text-center'>
                        "Examinez de près la colonne pour trouver la
                        cause de la maladie" Hippocrate
                    </h3>
                    <div className='grid lg:grid-cols-4 md:grid-cols-3 md:max-w-[90%] mx-auto gap-4 p-4'>
                        <Cards />
                        <Cards />
                        <Cards />
                        <Cards />
                    </div>
                </section>
            </main>
        </>
    );
}

export async function getStaticProps() {
    try {
        const response = await axios.get(
            'http://localhost:3000/api/navigationItems'
        );
        const navigationItems = response.data.navigationItems;

        return {
            props: { navigationItems },
        };
    } catch (error) {
        console.log(error);

        return {
            props: { navigationItems: null },
        };
    }
}
