// Libraries
import Head from 'next/head';
import Image from 'next/image';

// Components
import Header from '../Components/Header';
import Hero from '../Components/Hero';

export default function Home() {
  // JSX
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main>
        <header className='p-8 bg-[#3D9BE9]'>
          <Header />
        </header>
        <section className=''>
          <Hero />
        </section>
      </main>
    </>
  );
}
